config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  resources 'events'
  resources 'imgs'
  resources 'places'
  resources 'tags'
  get 'tags/:id/img'=> 'tags#img'
  patch "/tags/:id/imgset"=> 'tags#imgset'
  get 'tags/:id/url'=> 'tags#url'
  post "/tags/:id/urlset"=> 'tags#urlset'
  resources 'entries'
  get 'urls'=> 'urls#index'
  get 'urls/facebook'
  get 'urls/twitter'
  get 'urls/instagram'
  get 'pages/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  get 'feeds/show/:id/:page' => 'feeds#show'
  get 'inquiry' => 'inquiry#index'              # 入力画面
   post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
   post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  is_impressionable
  #acts_as_taggable_on :tags # entry.label_list が追加される
  acts_as_taggable
  mount_uploader :image, ImageUploader
  #just_define_datetime_picker :published
  belongs_to :feed
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :tag
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :entries, dependent: :destroy
    belongs_to :url
end

app/models/img.rb
class Img < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 10
  belongs_to :tag
  acts_as_mappable
end

app/models/rate.rb
class Rate < ApplicationRecord
    belongs_to :tag
    belongs_to :url
end

app/models/tag.rb
class Tag < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
  has_one :place, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :urls
  has_many :rates
  belongs_to :tagtype,required: false
  accepts_nested_attributes_for :event
  #has_many :follows_from, class_name: Follow, foreign_key: :from_tag_id, dependent: :destroy
  #has_many :follows_to,   class_name: Follow, foreign_key: :to_tag_id,   dependent: :destroy
  #has_many :following, through: :follows_from, source: :to_tag
  #has_many :followed,  through: :follows_to,   source: :from_tag
end

app/models/tagtype.rb
class Tagtype < ApplicationRecord
  has_many :tags
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :rates
  belongs_to :tag,required: false
  mount_uploader :image, ImageUploader
end

app/controllers/feeds_controller.rb
class FeedsController < InheritedResources::Base
  before_action :user_check, only: [:index,:new,:edit,:update]
  def show
    @feed = Feed.find(params[:id])
    @entry = @feed.entries.page(params[:page]).order('published desc')
  end
  private
    def feed_params
      params.require(:feed).permit(:name, :rss, :description)
    end

    def user_check
      if current_admin_user.nil?
        redirect_to("/")
      end
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tagtypes_helper.rb
module TagtypesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/feeds/_form.html.erb
<%= simple_form_for(@feed) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.rss %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<div class="container">
  <div class="card text-center">
    <div class="card-body">
      <h1 class="card-title h5"><%= @feed.name %></h1>
      <p class="card-text"><%= @feed.description %></p>
      <%= link_to "サイトに移動する", "#{@feed.url.url}", { :class => "btn btn-primary",:target=>"_blank" }  %>
    </div>
    <div class="card-footer text-muted">
      記事数：<%= @entry.total_count %>
    </div>
  </div>
</div>
<%= paginate @entry %>
<div class="masonry-container">
    <% @entry.each do |r| %>
      <div class="mas-box">
        <%= link_to(entry_path(r)) do %>
          <div class="bbox">
            <%= image_tag r.image.mid.url if r.image?  %>
            <%= r.title %>
            <div class="row entryitem">
              <div class="col"><%= time_ago_in_words(r.published)+"前" %></div>
              <div class="col right"><%= if r.author.present? then r.author elsif r.feed.present? then r.feed.name  end %></div>
            </div>
          </div>
        <% end %>
        <div  class="tags">
          <% r.tags.each do |tag| %>
            <%= link_to(tag_path(tag)) do%>
            <%= p tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
</div>

<%= paginate @entry %>