config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  resources 'events'
  resources 'imgs'
  resources 'places'
  resources 'tags'
  get 'tags/:id/img'=> 'tags#img'
  patch "/tags/:id/imgset"=> 'tags#imgset'
  get 'tags/:id/url'=> 'tags#url'
  post "/tags/:id/urlset"=> 'tags#urlset'
  resources 'entries'
  get 'urls'=> 'urls#index'
  get 'urls/facebook'
  get 'urls/twitter'
  get 'urls/instagram'
  get 'pages/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  get 'feeds/show/:id/:page' => 'feeds#show'
  get 'inquiry' => 'inquiry#index'              # 入力画面
   post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
   post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  is_impressionable
  #acts_as_taggable_on :tags # entry.label_list が追加される
  acts_as_taggable
  mount_uploader :image, ImageUploader
  #just_define_datetime_picker :published
  belongs_to :feed
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :tag
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :entries, dependent: :destroy
    belongs_to :url
end

app/models/img.rb
class Img < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 10
  belongs_to :tag
  acts_as_mappable
end

app/models/rate.rb
class Rate < ApplicationRecord
    belongs_to :tag
    belongs_to :url
end

app/models/tag.rb
class Tag < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
  has_one :place, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :urls
  has_many :rates
  belongs_to :tagtype,required: false
  accepts_nested_attributes_for :event
  #has_many :follows_from, class_name: Follow, foreign_key: :from_tag_id, dependent: :destroy
  #has_many :follows_to,   class_name: Follow, foreign_key: :to_tag_id,   dependent: :destroy
  #has_many :following, through: :follows_from, source: :to_tag
  #has_many :followed,  through: :follows_to,   source: :from_tag
end

app/models/tagtype.rb
class Tagtype < ApplicationRecord
  has_many :tags
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :rates
  belongs_to :tag,required: false
  mount_uploader :image, ImageUploader
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController
  include MyUtility
  def index
    gettlist
    gon.tlist = @tlist
    @img = Img.page(params[:page])
  end

  def show
    gettlist
    gon.tlist = @tlist
    @img = Img.find(params[:id])
    impressionist(@img, nil, :unique => [:session_hash])
    @page_views = @img.impressionist_count
    @imgs=@img.find_related_tags.limit(6)
  end

  def new

  end

  def create
    @img = Img.new(img_params)
    if @img.save
      redirect_to img_path(@img)
    else
      render :action => 'new'
    end
  end

  def edit
   @img = Img.find(params[:id])
   @all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name);
  end

  def update
    @img = Img.find(params[:id])
    if @img.update(img_params)
      redirect_to img_path(@img)
    else
      render :action => 'edit'
    end
  end

  def img_params
    params.require(:img).permit(:title,:tag_list,:image,:inyo)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tagtypes_helper.rb
module TagtypesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/imgs/edit.html.erb
<div class="container">
  <%= bootstrap_form_for(@img,url: {action: 'update'}, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
    <%= f.text_field :title, wrapper: { class: 'row' } %>
    <%= f.file_field :image, wrapper: { class: 'row' } %>
    <%= f.text_field :inyo, wrapper: { class: 'row' } %>
    <%= f.text_field :tag_list, value: @img.tag_list.join(","), wrapper: { class: 'row' }  %>
    <%= f.submit "完了",{ class: 'btn btn-primary' }%>
  <% end %>
  <ui id="alltag">
    <%= @all_tag_list.join(",")%>
  </ui>
</div>
<script type="text/javascript">
  $(function() {
    $(".datepicker").datepicker({dateFormat: 'yy-mm-dd'});
    alltag = (document.getElementById('alltag')).innerHTML;
    tagary = alltag.split(',');
    $('#tag_tag_list').tagit({
      singleField: true,
      availableTags: tagary,
    });
  });
</script>

app/views/imgs/index.html.erb
<div class="txc">
<h1 class="h2">画像一覧</h1>
</div>
<%= paginate @img %>
<div class="masonry-container">
    <% @img.each do |r| %>
      <div class="mas-box">
        <%= link_to(img_path(r)) do %>
          <div class="bbox">
            <%= image_tag r.image.mid.url if r.image?  %>
            <%= r.title %>
            <div class="row imgitem">
              <div class="col"><%= time_ago_in_words(r.created_at)+"前" %></div>
            </div>
          </div>
        <% end %>
        <div  class="tags">
          <% r.tags.each do |tag| %>
            <%= link_to(tag_path(tag)) do%>
            <%= p tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
</div>
<%= paginate @img %>

app/views/imgs/show.html.erb
<div class="container">
  <%= provide(:title, "#{@img.title}") %>
  <h1><%= @img.title %></h1>
  <% if !current_admin_user.nil? %>
    <%= number_with_delimiter(@page_views) %>
    <%= link_to(edit_img_path(@img)) do %>
    編集
    <% end %>
  <% end %>
  <div  class="stags">
    <% @img.tags.each do |tag| %>
      <%= link_to(tag_path(tag), class: "btn btn-primary btn-sm") do%>
      <%= p tag.name %>
      <% end %>
    <% end %>
  </div>
    <p>
    <i><%= @img.created_at.to_s(:published) %> </i>
  </p>
<%= image_tag @img.image.url, :class => "float-left pdr10 eimg" if @img.image?  %>
    <%= simple_format(@img.content) %></p>
</div>
<div id="masonry-container">
    <% @imgs.each do |r| %>
      <div class="mas-box">
        <%= link_to(img_path(r)) do %>
          <div class="bbox">
            <%= image_tag r.image.mid.url if r.image?  %>
            <%= r.title %>
            <div class="row imgitem">
            </div>
          </div>
        <% end %>
        <div  class="tags">
          <% r.tags.each do |tag| %>
            <%= link_to(tag_path(tag)) do%>
            <%= p tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>