config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  resources 'events'
  resources 'imgs'
  resources 'places'
  resources 'tags'
  get 'tags/:id/img'=> 'tags#img'
  patch "/tags/:id/imgset"=> 'tags#imgset'
  get 'tags/:id/url'=> 'tags#url'
  post "/tags/:id/urlset"=> 'tags#urlset'
  resources 'entries'
  get 'urls'=> 'urls#index'
  get 'urls/facebook'
  get 'urls/twitter'
  get 'urls/instagram'
  get 'pages/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  get 'feeds/show/:id/:page' => 'feeds#show'
  get 'inquiry' => 'inquiry#index'              # 入力画面
   post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
   post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  is_impressionable
  #acts_as_taggable_on :tags # entry.label_list が追加される
  acts_as_taggable
  mount_uploader :image, ImageUploader
  #just_define_datetime_picker :published
  belongs_to :feed
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :tag
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :entries, dependent: :destroy
    belongs_to :url
end

app/models/img.rb
class Img < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 10
  belongs_to :tag
  acts_as_mappable
end

app/models/rate.rb
class Rate < ApplicationRecord
    belongs_to :tag
    belongs_to :url
end

app/models/tag.rb
class Tag < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
  has_one :place, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :urls
  has_many :rates
  belongs_to :tagtype,required: false
  accepts_nested_attributes_for :event
  #has_many :follows_from, class_name: Follow, foreign_key: :from_tag_id, dependent: :destroy
  #has_many :follows_to,   class_name: Follow, foreign_key: :to_tag_id,   dependent: :destroy
  #has_many :following, through: :follows_from, source: :to_tag
  #has_many :followed,  through: :follows_to,   source: :from_tag
end

app/models/tagtype.rb
class Tagtype < ApplicationRecord
  has_many :tags
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :rates
  belongs_to :tag,required: false
  mount_uploader :image, ImageUploader
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include MyUtility
  def index
    gettlist
    gon.tlist = @tlist
    if params[:key].present?
      @entry = Entry.where("replace(replace(content,' ',''),'　','') like ? OR title like ?" ,"%" + params[:key] + "%", "%" + params[:key] + "%",).page(params[:page]).order('published desc')
      @key= params[:key];
    else
      @entry = Entry.page(params[:page]).order('published desc')
    end
  end

  def show
    gettlist
    gon.tlist = @tlist
    @entry = Entry.find(params[:id])
    impressionist(@entry, nil, :unique => [:session_hash])
    @page_views = @entry.impressionist_count
    if @entry.content.blank?
      @entry.content="この記事の内容は掲載元にてご覧ください"
    end
    @entries=@entry.find_related_tags.limit(6)
    if @entries.present?
    else
      @feed = Feed.find(@entry.feed.id)
      @entries = @feed.entries.where.not(id: params[:id]).order('published desc').limit(6)
    end
    #tag_ids = @entry.tags.map { |c| c.id }.join(',')
    #@all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
    #@entries = Entry.includes(:tags).where(entries_tags: {tag_id: .tag_ids}).references(:tags)
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tagtypes_helper.rb
module TagtypesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/entries/index.html.erb
    <div id="wrapper">
      <div class="txc">
      <% if @key.present? %>
      <h1 class="h5">
          <%= "検索結果：#{@key} (#{@entry.total_count}件）" %>
      </h1>
      <% else %>
      <h1>カサリサ</h1>
      <p>
        カサリサ（カサマリサーチ）は、笠間に関する記事を紹介する個人運営サイトです。
      </p>
      <% end %>
    </div>
      <%= paginate @entry %>
      <div class="masonry-container">
          <% @entry.each do |r| %>
            <div class="mas-box">
              <%= link_to(entry_path(r)) do %>
                <div class="bbox">
                  <%= image_tag r.image.mid.url if r.image?  %>
                  <%= r.title %>
                  <div class="row entryitem">
                    <div class="col"><%= time_ago_in_words(r.published)+"前" %></div>
                    <div class="col right"><%= if r.author.present? then r.author elsif r.feed.present? then r.feed.name  end %></div>
                  </div>
                </div>
              <% end %>
              <div  class="tags">
                <% r.tags.each do |tag| %>
                  <%= link_to(tag_path(tag)) do%>
                  <%= p tag.name %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
      </div>
      <%= paginate @entry %>
    </div>

app/views/entries/show.html.erb
<div class="container">
  <%= provide(:title, "#{@entry.title}by#{@entry.author}") %>
  <h1><%= @entry.title %></h1>
  <% if !current_admin_user.nil? %>
  <%= number_with_delimiter(@page_views) %>
  <% end %>
  <div  class="stags">
    <% @entry.tags.each do |tag| %>
      <%= link_to(tag_path(tag), class: "btn btn-primary btn-sm") do%>
      <%= p tag.name %>
      <% end %>
    <% end %>
  </div>
    <p>
    <i><%= @entry.published.to_s(:published) %> by
      <%= link_to("/feeds/#{@entry.feed.id}") do%>
      <%= p @entry.author %>
      <% end %>
    </i>
  </p>
<%= image_tag @entry.image.url, :class => "float-left pdr10 eimg" if @entry.image?  %>
    <%= simple_format(@entry.content) %></p>
    <%= link_to("#{@entry.url}",:target=>"_blank") do%>
    <div class="clear"></div>
    <span type="button" class="btn btn-primary btn-lg btn-block mg10">掲載元で続きを読む</span>
    <% end %>
</div>
<div class="masonry-container">
    <% @entries.each do |r| %>
      <div class="mas-box">
        <%= link_to(entry_path(r)) do %>
          <div class="bbox">
            <%= image_tag r.image.mid.url if r.image?  %>
            <%= r.title %>
            <div class="row entryitem">
              <div class="col"><%= time_ago_in_words(r.published)+"前" %></div>
              <div class="col right"><%= if r.author.present? then r.author elsif r.feed.present? then r.feed.name  end %></div>
            </div>
          </div>
        <% end %>
        <div  class="tags">
          <% r.tags.each do |tag| %>
            <%= link_to(tag_path(tag)) do%>
            <%= p tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>