config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  resources 'events'
  resources 'imgs'
  resources 'places'
  resources 'tags'
  get 'tags/:id/img'=> 'tags#img'
  patch "/tags/:id/imgset"=> 'tags#imgset'
  get 'tags/:id/url'=> 'tags#url'
  post "/tags/:id/urlset"=> 'tags#urlset'
  resources 'entries'
  get 'urls'=> 'urls#index'
  get 'urls/facebook'
  get 'urls/twitter'
  get 'urls/instagram'
  get 'pages/show'
  resources :feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  get 'feeds/show/:id/:page' => 'feeds#show'
  get 'inquiry' => 'inquiry#index'              # 入力画面
   post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
   post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  is_impressionable
  #acts_as_taggable_on :tags # entry.label_list が追加される
  acts_as_taggable
  mount_uploader :image, ImageUploader
  #just_define_datetime_picker :published
  belongs_to :feed
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :tag
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :entries, dependent: :destroy
    belongs_to :url
end

app/models/img.rb
class Img < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 10
  belongs_to :tag
  acts_as_mappable
end

app/models/rate.rb
class Rate < ApplicationRecord
    belongs_to :tag
    belongs_to :url
end

app/models/tag.rb
class Tag < ApplicationRecord
  is_impressionable
  acts_as_taggable
  mount_uploader :image, ImageUploader
  has_one :place, dependent: :destroy
  has_one :event, dependent: :destroy
  has_many :urls
  has_many :rates
  belongs_to :tagtype,required: false
  accepts_nested_attributes_for :event
  #has_many :follows_from, class_name: Follow, foreign_key: :from_tag_id, dependent: :destroy
  #has_many :follows_to,   class_name: Follow, foreign_key: :to_tag_id,   dependent: :destroy
  #has_many :following, through: :follows_from, source: :to_tag
  #has_many :followed,  through: :follows_to,   source: :from_tag
end

app/models/tagtype.rb
class Tagtype < ApplicationRecord
  has_many :tags
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :rates
  belongs_to :tag,required: false
  mount_uploader :image, ImageUploader
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :destroy,:url,:urlset]
  before_action :user_check, only: [:new, :create,:edit,:update,:img,:imgset,:url,:urlset]
  include MyUtility

  def index
    gettlist
    gon.tlist = @tlist
    @tagtypes = Tagtype.all
    if params[:type].present?
      if params[:type]=="10"
        @tag = Tag.where(tagtype:nil).page(params[:page]).order('taggings_count desc')
      else
        @tag = Tag.where(tagtype:params[:type],oya: nil).page(params[:page]).order('taggings_count desc')
        @tagtype = Tagtype.find(params[:type])
      end
    else
      @tag = Tag.where(oya: nil).page(params[:page]).order('taggings_count desc').per(50)
    end
  end

  def show
    gettlist
    gon.tlist = @tlist
    @tag = Tag.find(params[:id])
    impressionist(@tag, nil, :unique => [:session_hash])
    @page_views = @tag.impressionist_count
    @imgs = Img.tagged_with(@tag.name).limit(4)
    @entry = Entry.page.tagged_with(@tag.name).order('published desc')
    @events = Tag.tagged_with(@tag.name).where(tagtype: 4)
  end

  def new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tag_path(@tag)
    else
      render :action => 'new'
    end
  end

  def edit
   @all_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name);
   @tag.event = Event.new if @tag.event.blank?
   @tag.place = Place.new if @tag.place.blank?
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag)
    else
      render :action => 'edit'
    end
  end

  def img
   @tag = Tag.find(params[:id])
  end

  def imgset
   @tag = Tag.find(params[:id])
   @img = Img.new(img_params)
   @img.tag_list.add(@tag.name)
   if @img.save
     redirect_to img_path(@img)
   else
     render :action => 'img'
   end
  end

  def url
  end

  def urlset
   @url = Url.new(url_params)
   @url.tag_id=@tag.id
   if @url.save
     redirect_to tag_path(@tag)
   else
     render :action => 'url'
   end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name,:read,:body,:tagtype_id,:tag_list,:image,:inyo,:oya,:facebook,:twitter,:instagram, event_attributes: [:start,:end,:etc,:place], place_attributes: [:adress])
    end

    def img_params
      params.require(:img).permit(:title,:image,:inyo)
    end

    def url_params
      params.require(:url).permit(:title,:image,:url)
    end

    def user_check
      if current_admin_user.nil?
        redirect_to("/")
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "カサリサ" # 自分のアプリ名を設定する
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tagtypes_helper.rb
module TagtypesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/tags/edit.html.erb
<div class="container">
  <%= bootstrap_form_for(@tag,url: {action: 'update'}, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
      <%= f.text_field :name, wrapper: { class: 'row' } %>
    <%= f.text_field :read, wrapper: { class: 'row' } %>
    <%= f.text_area :body, wrapper: { class: 'row' } %>
    <%= f.file_field :image, wrapper: { class: 'row' } %>
    <%= f.text_field :inyo, wrapper: { class: 'row' } %>
    <%= f.number_field :oya, wrapper: { class: 'row' } %>
    <%= f.text_field :tag_list, value: @tag.tag_list.join(","), wrapper: { class: 'row' }  %>
    <%= f.collection_select :tagtype_id, Tagtype.all, :id, :name, {}, wrapper: { class: 'row' } %>
    <%= f.text_field :facebook, wrapper: { class: 'row' } %>
    <%= f.text_field :twitter, wrapper: { class: 'row' } %>
    <%= f.text_field :instagram, wrapper: { class: 'row' } %>
    <div>ーーーーーーーイベントーーーーーーー</div>
    <%= f.fields_for :event, @tag.event do |pf| %>
          <%= pf.text_field :start,label: '開始',class: 'datepicker', wrapper: { class: 'row' } %>
          <%= pf.text_field :end,label: '終了',class: 'datepicker', wrapper: { class: 'row' } %>
          <%= pf.text_field :etc,label: 'その他情報', wrapper: { class: 'row' } %>
          <%= pf.text_field :kibo,label: '規模', wrapper: { class: 'row' } %>
          <%= pf.text_field :place,label: '場所', wrapper: { class: 'row' } %>
      <% end %>
      <div>ーーーーーーー場所ーーーーーーー</div>
      <%= f.fields_for :place, @tag.place do |pf| %>
            <%= pf.text_field :adress, wrapper: { class: 'row' } %>
        <% end %>
    <%= f.submit "完了",{ class: 'btn btn-primary' }%>
  <% end %>
  <ui id="alltag">
    <%= @all_tag_list.join(",")%>
  </ui>
</div>
<script type="text/javascript">
  $(function() {
    $(".datepicker").datepicker({dateFormat: 'yy-mm-dd'});
    alltag = (document.getElementById('alltag')).innerHTML;
    tagary = alltag.split(',');
    $('#tag_tag_list').tagit({
      singleField: true,
      availableTags: tagary,
    });
  });
</script>

app/views/tags/img.html.erb
<div class="container">
  <%= @tag.name %>の画像追加
  <%= bootstrap_form_for(Img.new,url: {action: 'imgset'}, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
    <%= f.text_field :title, wrapper: { class: 'row' } %>
    <%= f.file_field :image, wrapper: { class: 'row' } %>
    <%= f.text_field :inyo, wrapper: { class: 'row' } %>
    <%= f.submit "完了",{ class: 'btn btn-primary' }%>
  <% end %>
</div>

app/views/tags/index.html.erb
<div id="wrapper">
  <div class="txc">
    <% if @tagtype.present? %>
      <h1 class="h2">
          <%= "#{@tagtype.name} (#{@tag.total_count}件）" %>
      </h1>
    <% else %>
      <h1 class="h2">タグ一覧</h1>
      <% if !current_admin_user.nil? %>
      <div><%= link_to "新規",new_tag_path %></div>
      <% end %>
    <% end %>
    <div  class="stags mg10">
      <%= link_to("/tags", class: "btn btn-primary btn-sm") do%>
        <%= p "すべて" %>
      <% end %>
      <% @tagtypes.each do |tt| %>
        <%= link_to("/tags?type=#{tt.id}", class: "btn btn-primary btn-sm") do%>
        <%= p tt.name %>
        <% end %>
      <% end %>
      <%= link_to("/tags?type=10", class: "btn btn-primary btn-sm") do%>
        <%= p "その他" %>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @tag %>
    <div id="wrapper">
      <div class="masonry-container">
        <% @tag.each do |r| %>
            <div class="mas-box">
              <%= link_to(tag_path(r)) do %>
              <div class="bbox">
              <%= "#{r.name}(#{r.taggings_count})" %>
              <% if r.rates.present? %>
                <div>
                <%
                avrate=r.rates.average(:rate).round(1)
                avrate=avrate.round*2/2*10
                 %>
                <span class="rate rate<%= avrate %>"></span>
                </div>
              <% end %>
              </div>
              <% end %>
              <% if !current_admin_user.nil? %>
                <%= link_to(edit_tag_path(r)) do %>
                編集
                <% end %>
              <% end %>
              <div class="tr">
                <% if r.urls.present? %>
                  <% r.urls.each do |u| %>
                    <%= link_to(u.url,:target=>"_blank") do %>
                      <%= fa_icon "globe" %>
                    <% end %>
                  <% end %>
                <% end %>
                <% if r.instagram? %>
                <%= link_to("https://www.instagram.com/#{r.instagram}",:target=>"_blank") do %>
                  <%= fa_icon "instagram" %>
                <% end %>
                <% end %>
                <% if r.facebook? %>
                <%= link_to("https://www.facebook.com/#{r.facebook}",:target=>"_blank") do %>
                  <%= fa_icon "facebook",class:"fb" %>
                <% end %>
                <% end %>
                <% if r.twitter? %>
                <%= link_to("https://twitter.com/#{r.twitter}",:target=>"_blank") do %>
                  <%= fa_icon "twitter",class:"tw" %>
                <% end %>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
<%= paginate @tag %>

app/views/tags/new.html.erb
<%= simple_form_for Tag.new do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/tags/show.html.erb
<%= provide(:title,"#{@tag.name}") %>
<% if !current_admin_user.nil? %>
  <%= number_with_delimiter(@page_views) %>
  <%= link_to(edit_tag_path(@tag)) do %>
  編集
  <% end %>
  <%= link_to("#{@tag.id}/img") do %>
  画像
  <% end %>
  <%= link_to("#{@tag.id}/url") do %>
  URL
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <% if @tag.image? %>
    <div class="col-sm-3 imgf">
      <%= image_tag @tag.image.mid.url %>
    </div>
    <% end %>
    <div class="col-sm-9">
  <% if @tag.read? %>
  <div class="gray small"><%= @tag.read %></div>
  <% end %>
  <h3><%= @tag.name %></h3>
  <% if @tag.rates.present? %>
    <div class="small">
      <%
      avrate=@tag.rates.average(:rate).round(1)
      avrate2=avrate.round*2/2*10
       %>
      <span class="rate rate<%= avrate2 %>"></span>
      <span class="rating">
      <span class="average"><%= avrate %></span>
      </span>
      <div>
        <% @tag.rates.each do |r| %>
          |
          <span class="lead"><%= r.rate %></span>
          <span class="gray"><%= r.rcount %>票</span>
          <%= link_to r.url.title,r.siteurl,target:"_blank" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="stags">
    <% @tag.tags.each do |tag| %>
      <%= link_to(tag_path(tag), class: "btn btn-primary btn-sm") do%>
      <%= p tag.name %>
      <% end %>
    <% end %>
  </div>
      <div>
        <%= @tag.body %>
        <% if @tag.place.present? %>
          <%= @tag.place.adress %>
          <%= @tag.place.tel %>
          <%= @tag.place.open %>
          <%= @tag.place.parking %>
        <% end %>
        <% if @tag.event.present? %>
          <% if @tag.event.start.present? %>
            <%= @tag.event.start.strftime("%m/%d")  %>
            <span class="badge badge-secondary"><%= %w(日 月 火 水 木 金 土)[@tag.event.start.wday] %></span>
            <% if @tag.event.start !=@tag.event.end %>
              <%= "～#{@tag.event.end.strftime("%m/%d")}" %>
              <span class="badge badge-secondary"><%= %w(日 月 火 水 木 金 土)[@tag.event.end.wday] %></span>
            <% end %>
          <% end %>
          <%= @tag.event.etc %>
        <% end %>
      </div>
    </div>
  </div>

<div>
  <%= fa_icon "file-o" %>
  <%= @tag.taggings_count %>
  <% if @tag.urls.present? %>
    <% @tag.urls.each do |u| %>
      <%= link_to(u.url,:target=>"_blank") do %>
        <%= fa_icon "globe" %>
      <% end %>
    <% end %>
  <% end %>
  <% if @tag.instagram? %>
  <%= link_to("https://www.instagram.com/#{@tag.instagram}",:target=>"_blank") do %>
    <%= fa_icon "instagram" %>
  <% end %>
  <% end %>
  <% if @tag.facebook? %>
  <%= link_to("https://www.facebook.com/#{@tag.facebook}",:target=>"_blank") do %>
    <%= fa_icon "facebook",class:"fb" %>
  <% end %>
  <% end %>
  <% if @tag.twitter? %>
  <%= link_to("https://twitter.com/#{@tag.twitter}",:target=>"_blank") do %>
    <%= fa_icon "twitter",class:"tw" %>
  <% end %>
  <% end %>
</div>
</div>
<div class="row d-flex justify-content-center mg10">
    <% @imgs.each do |r| %>
        <div class="col-sm-3">
        <%= link_to(img_path(r)) do %>
          <div class="bbox">
            <%= image_tag r.image.mid.url if r.image?  %>
            <%= r.title %>
            <div class="row imgitem">
              <div class="col"><%= time_ago_in_words(r.created_at)+"前" %></div>
            </div>
          </div>
        <% end %>
        <div  class="tags">
          <% r.tags.each do |tag| %>
            <%= link_to(tag_path(tag)) do%>
            <%= p tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
</div>
<% if @events.present? %>
<div class="container">
<h4>イベント一覧</h4>
</div>
<div id="wrapper">
  <div class="masonry-container">
    <% @events.each do |r| %>
      <%= render partial: 'shared/event', locals: { r: r.event ,v:0} %>
    <% end %>
  </div>
</div>
<% end %>
<% if @entry.present? %>
<div class="container">
<h4>記事一覧</h4>
</div>
  <% end %>
  <%= paginate @entry %>
  <div id="wrapper">
    <div class="masonry-container">
        <% @entry.each do |r| %>
          <div class="mas-box">
            <%= link_to(entry_path(r)) do %>
              <div class="bbox">
                <%= image_tag r.image.mid.url if r.image?  %>
                <%= r.title %>
                <div class="row entryitem">
                  <div class="col"><%= time_ago_in_words(r.published)+"前" %></div>
                  <div class="col right"><%= if r.author.present? then r.author elsif r.feed.present? then r.feed.name  end %></div>
                </div>
              </div>
            <% end %>
            <div  class="tags">
              <% r.tags.each do |tag| %>
                <%= link_to(tag_path(tag)) do%>
                <%= p tag.name %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
  <%= paginate @entry %>

app/views/tags/url.html.erb
<div class="container">
  <%= @tag.name %>のURL追加
  <%= bootstrap_form_for(Url.new,url: {action: 'urlset'}, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
    <%= f.text_field :title, wrapper: { class: 'row' } %>
    <%= f.text_field :url, wrapper: { class: 'row' } %>
    <%= f.file_field :image, wrapper: { class: 'row' } %>
    <%= f.submit "完了",{ class: 'btn btn-primary' }%>
  <% end %>
</div>